version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/core"
    schedule:
      interval: "weekly"
    labels:
      - "type: ci/cd"
      - "priority: low"

  - package-ecosystem: "gomod"
    directory: "/sim"
    schedule:
      interval: "weekly"
    labels:
      - "type: ci/cd"
      - "priority: low"

  - package-ecosystem: "gomod"
    directory: "/game"
    schedule:
      interval: "weekly"
    labels:
      - "type: ci/cd"
      - "priority: low"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type: ci/cd"
      - "priority: low"
